language: java
jdk:
  - oraclejdk7

env:
  - HADOOP_PROFILE=default
  - HADOOP_PROFILE=hadoop-1
  - HADOOP_PROFILE=cdh4
  - HADOOP_PROFILE=cdh5
cache:
  directories:
    - $HOME/.m2

install: mvn -q install -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true -DjavaVersion=1.7
before_script: umask 0022
script: mvn test -P $HADOOP_PROFILE -DjavaVersion=1.7
